function txt = compose_params_text(pars, Er)
f = @(x) sprintf('%g', x);
if isfield(pars, 'tau_h_ms')
    txt = sprintf(['gBar = %s mS\nEr = %s mV\n', ...
                   'V1/2_m = %s mV, b_m = %s, tau_m = %s ms\n', ...
                   'V1/2_h = %s mV, b_h = %s, tau_h = %s ms'], ...
        f(pars.gBar_mS), f(Er), ...
        f(pars.Vhalf_m), f(pars.b_m), f(pars.tau_m_ms), ...
        f(pars.Vhalf_h), f(pars.b_h), f(pars.tau_h_ms));
else
    txt = sprintf(['gBar = %s mS\nEr = %s mV\n', ...
                   'V1/2 = %s mV, b = %s, tau = %s ms'], ...
        f(pars.gBar_mS), f(Er), f(pars.Vhalf_m), f(pars.b_m), f(pars.tau_m_ms));
end
end
